# ACT PERTEMUAN 2

ADRIAN DERMAWAN BUDYANTO - 240401020213

In [51]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split

url = "https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv"
df = pd.read_csv(url)

display(df.head())

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [16]:
print("Struktur Data:")
rows, cols = df.shape
print(f"Jumlah Baris: {rows}")
print(f"Jumlah Kolom: {cols}")
print(f"Daftar Nama Kolom : {df.columns.tolist()}")

Struktur Data:
Jumlah Baris: 891
Jumlah Kolom: 12
Daftar Nama Kolom : ['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp', 'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked']

In [25]:
print("Missing Values:")
missing_data = pd.DataFrame({
    'Missing': df.isnull().sum(),
    'Percentage (%)': (df.isnull().sum() / len(df)) * 100
})
display(missing_data[missing_data['Missing'] > 0])

Missing Values:

          Missing  Percentage (%)
Age           177       19.865320
Cabin         687       77.104377
Embarked        2        0.224467

In [30]:
survival_rate = df['Survived'].mean() * 100
print(f"\nPersentase penumpang yang selamat: {survival_rate:.2f}%")

Persentase penumpang yang selamat: 38.38%

In [34]:
female_c1 = df[(df['Sex'] == 'female') & (df['Pclass'] == 1)]
jml_female_c1 = len(female_c1)
avg_age_female_c1 = female_c1['Age'].mean()

print(f" Analisis Wanita Kelas 1:")
print(f"- Jumlah Penumpang: {jml_female_c1}")
print(f"- Rata-rata Usia  : {avg_age_female_c1:.2f} tahun")

 Analisis Wanita Kelas 1:
- Jumlah Penumpang: 94
- Rata-rata Usia  : 34.61 tahun

In [40]:
print("Tingkat Keselamatan Berdasarkan Kelas:")
class_survival = df.groupby('Pclass')['Survived'].mean() * 100
print(class_survival)
print(f"Kelas dengan tingkat keselamatan tertinggi: Kelas {class_survival.idxmax()}")

Tingkat Keselamatan Berdasarkan Kelas:
Pclass
1    62.962963
2    47.282609
3    24.236253
Name: Survived, dtype: float64
Kelas dengan tingkat keselamatan tertinggi: Kelas 1

In [57]:
# Encoding Data
df['Sex_enc'] = (df['Sex'] == 'female').astype(int)
df['FamilySize'] = df['SibSp'] + df['Parch'] + 1

features = ['Pclass', 'Sex_enc', 'Age', 'Fare', 'FamilySize']
df_clean = df[features + ['Survived']].dropna()

X = df_clean[features]
y = df_clean['Survived']

# Split & scale
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
scaler = StandardScaler()
X_train_s = scaler.fit_transform(X_train)
X_test_s  = scaler.transform(X_test)

# Model
model = LogisticRegression(max_iter=500)
model.fit(X_train_s, y_train)
y_pred = model.predict(X_test_s)

# Hasil
print(f"Akurasi Model: {accuracy_score(y_test, y_pred)*100:.2f}%\n")

coef_df = pd.DataFrame({
    'Fitur'     : features,
    'Koefisien' : model.coef_[0].round(3)
}).sort_values('Koefisien', key=abs, ascending=False)

print("Faktor Dominan Keselamatan : (Urut)")
print(coef_df.to_string(index=False))

Akurasi Model: 74.13%

Faktor Dominan Keselamatan : (Urut)
     Fitur  Koefisien
   Sex_enc      1.325
    Pclass     -1.010
       Age     -0.689
FamilySize     -0.301
      Fare      0.114