# ACT PERTEMUAN 3

Adrian Dermawan Budyanto - 240401020213

In [3]:
# ============================================
# PIPELINE DATA CLEANING — HOUSING DATASET
# ============================================
import pandas as pd
import numpy as np
from scipy.stats.mstats import winsorize

# STEP 0 — Load & eksplorasi awal
df = pd.read_csv('https://files.ajinf.my.id/housing_dirty.csv')
print('Shape awal:', df.shape)
print(df.isnull().sum())

Shape awal: (130, 7)
id               0
luas_m2         18
harga_juta      17
kota             0
kamar           10
tahun_bangun     0
kondisi          0
dtype: int64

In [4]:
# STEP 1 — Hapus Duplikat
df.drop_duplicates(inplace=True)
print('Setelah hapus duplikat:', df.shape)

Setelah hapus duplikat: (130, 7)

In [11]:
# STEP 2 — Normalisasi String
df['kota'] = df['kota'].str.strip().str.title()
df['kondisi'] = df['kondisi'].str.strip().str.lower()

display(df[["kota", "kondisi"]].head())

    kota kondisi
0  Jogja    baik
1  Medan   bagus
2  Depok    baik
3    Ygy    baik
4  Medan  sedang

In [13]:
# STEP 3 — Imputasi Missing Values
df['luas_m2'] = df['luas_m2'].fillna(df['luas_m2'].median())
df['harga_juta'] = df['harga_juta'].fillna(df['harga_juta'].median())
df['kamar'] = df['kamar'].fillna(df['kamar'].mode()[0])

print("Missing value setelah imputasi:", df.isnull().sum().sum())
print(df.isnull().sum())

Missing value setelah imputasi: 0
id              0
luas_m2         0
harga_juta      0
kota            0
kamar           0
tahun_bangun    0
kondisi         0
dtype: int64

In [15]:
# STEP 4 — Tangani Outlier (IQR Fence)
for col in ["harga_juta", "luas_m2", "tahun_bangun"]:
    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)
    IQR = Q3 - Q1

    lower = Q1 - 1.5 * IQR
    upper = Q3 + 1.5 * IQR

    df[col] = df[col].clip(lower, upper)

    print(f"{col}")
    print(f"Batas Bawah: {lower}")
    print(f"Batas Atas : {upper}")
    print()

harga_juta
Batas Bawah: -422.75
Batas Atas : 1719.25

luas_m2
Batas Bawah: -145.225
Batas Atas : 512.9749999999999

tahun_bangun
Batas Bawah: 1960.5
Batas Atas : 2042.5

In [16]:
# STEP 5 — Validasi & Ekspor
assert df.isnull().sum().sum() == 0, 'Masih ada missing!'
assert df.duplicated().sum() == 0, 'Masih ada duplikat!'

print('Shape akhir:', df.shape)
df.to_csv('housing_clean.csv', index=False)

print('Dataset bersih tersimpan!')
display(df.head())

Shape akhir: (130, 7)
Dataset bersih tersimpan!

   id  luas_m2  harga_juta   kota  kamar  tahun_bangun kondisi
0   1    297.0      1084.0  Jogja    2.0        2000.0    baik
1   2    254.0       761.0  Medan    1.0        1995.0   bagus
2   3    249.7       895.0  Depok    1.0        1983.0    baik
3   4     49.7       178.0    Ygy    5.0        2013.0    baik
4   5    133.4       424.0  Medan    5.0        2004.0  sedang